version: '3.8'

services:
  aidash:
    build: .
    container_name: aidash-os
    restart: always
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./backend/users.json:/app/backend/users.json
      - ./server.log:/app/server.log
      - /:/host:rw
      - /var/run/dbus:/var/run/dbus
      # Using /var/run/wpa_supplicant to avoid symlink recursion errors
      - /var/run/wpa_supplicant:/var/run/wpa_supplicant
    privileged: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    ipc: host
